# Nama workflow yang akan muncul di tab Actions
name: Python Code Quality Check

# Pemicu kapan workflow ini harus dijalankan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Daftar pekerjaan (jobs) yang harus dilakukan
jobs:
  # Nama pekerjaan pertama: 'linter-check'
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linter with flake8
        run: flake8

  # Nama pekerjaan kedua: 'build-and-push-docker' (CD)
  build-and-push-docker:
    # Pekerjaan ini hanya akan dijalankan jika 'linter-check' berhasil
    needs: linter-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Build dan push image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/demo-ml-model:latest
